export interface Client {
  id: string;
  client_type?: string | null;
  archived?: boolean | null;
  is_archived?: boolean;
  // Common fields
  name?: string | null;
  bin_iin?: string | null;
  address?: string | null;
  actual_address?: string | null;
  phone?: string | null;
  email?: string | null;
  photo_35x45?: string | null;
  contact_info?: string | null;
  owner_id?: number | null;
  display_name?: string | null;
  primary_phone?: string | null;
  primary_email?: string | null;
  created_at: string;
  updated_at: string;
  
  // Legal entity specific fields (in main table)
  contact_person_position?: string | null;
  bank_name?: string | null;
  iban?: string | null;
  bik?: string | null;
  kbe?: string | null;
  
  // Legal profile (from client_legal_profiles table)
  legal_profile?: {
    company_name?: string;
    bin?: string;
    legal_form?: string;
    director_full_name?: string;
    contact_person_name?: string;
    contact_person_position?: string;
    contact_person_phone?: string;
    contact_person_email?: string;
    legal_address?: string;
    actual_address?: string;
    bank_name?: string;
    iban?: string;
    bik?: string;
    kbe?: string;
    tax_regime?: string;
    website?: string;
    industry?: string;
    company_size?: string;
    additional_info?: string;
  };

  // Individual profile (from client_individual_profiles table)
  individual_profile?: {
    last_name?: string;
    first_name?: string;
    middle_name?: string;
    iin?: string;
    id_number?: string;
    passport_series?: string;
    passport_number?: string;
    registration_address?: string;
    actual_address?: string;
    country?: string;
    trip_purpose?: string;
    birth_date?: string;
    birth_place?: string;
    citizenship?: string;
    sex?: string;
    marital_status?: string;
    passport_issue_date?: string;
    passport_expire_date?: string;
    previous_last_name?: string;
    spouse_name?: string;
    spouse_contacts?: string;
    has_children?: boolean;
    children_list?: any;
    education_level?: string;
    education?: string;
    job?: string;
    trips_last5_years?: string;
    relatives_in_destination?: string;
    trusted_person?: string;
    specialty?: string;
    trusted_person_phone?: string;
    driver_license_number?: string;
    education_institution_name?: string;
    education_institution_address?: string;
    position?: string;
    visas_received?: string;
    visa_refusals?: string;
    height?: number;
    weight?: number;
    driver_license_categories?: any;
    therapist_name?: string;
    clinic_name?: string;
    diseases_last3_years?: string;
    additional_info?: string;
  };

  // Individual specific fields (from client_individual_profiles table) - kept for backward compatibility
  last_name?: string | null;
  first_name?: string | null;
  middle_name?: string | null;
  iin?: string | null;
  id_number?: string | null;
  id_issue_date?: string | null;
  id_expire_date?: string | null;
  passport_series?: string | null;
  passport_number?: string | null;
  passport_issue_date?: string | null;
  passport_expire_date?: string | null;
  registration_address?: string | null;
  residential_address?: string | null;
  country?: string | null;
  country_other?: string | null;
  trip_purpose?: string | null;
  trip_purpose_other?: string | null;
  birth_date?: string | null;
  birth_place?: string | null;
  citizenship?: string | null;
  sex?: string | null;
  marital_status?: string | null;
  previous_last_name?: string | null;
  spouse_name?: string | null;
  spouse_contacts?: string | null;
  has_children?: boolean | null;
  children_list?: any | null;
  education_level?: string | null;
  specialty?: string | null;
  education_institution?: string | null;
  education_institution_address?: string | null;
  education_institution_name?: string | null;
  education?: string | null;
  job?: string | null;
  position?: string | null;
  trips_last5_years?: string | null;
  visas_received?: string | null;
  visa_refusals?: string | null;
  relatives_in_destination?: string | null;
  trusted_person?: string | null;
  trusted_person_phone?: string | null;
  height?: number | null;
  weight?: number | null;
  driver_license_number?: string | null;
  driver_license_issue_date?: string | null;
  driver_license_expire_date?: string | null;
  driver_license_categories?: any | null;
  therapist_name?: string | null;
  clinic_name?: string | null;
  diseases_last3_years?: string | null;
  additional_info?: string | null;
}

export type CreateClientRequest = Omit<Client, "id" | "created_at" | "updated_at"> & {
  client_type?: string;
  legal_profile?: {
    company_name?: string;
    bin?: string;
    legal_form?: string;
    director_full_name?: string;
    contact_person_name?: string;
    contact_person_position?: string;
    contact_person_phone?: string;
    contact_person_email?: string;
    legal_address?: string;
    actual_address?: string;
    bank_name?: string;
    iban?: string;
    bik?: string;
    kbe?: string;
    tax_regime?: string;
    website?: string;
    industry?: string;
    company_size?: string;
    additional_info?: string;
  };
  individual_profile?: {
    last_name?: string;
    first_name?: string;
    middle_name?: string;
    iin?: string;
    id_number?: string;
    passport_series?: string;
    passport_number?: string;
    registration_address?: string;
    actual_address?: string;
    country?: string;
    trip_purpose?: string;
    birth_date?: string;
    birth_place?: string;
    citizenship?: string;
    sex?: string;
    marital_status?: string;
    passport_issue_date?: string;
    passport_expire_date?: string;
    previous_last_name?: string;
    spouse_name?: string;
    spouse_contacts?: string;
    has_children?: boolean;
    children_list?: any;
    education_level?: string;
    education?: string;
    job?: string;
    trips_last5_years?: string;
    relatives_in_destination?: string;
    trusted_person?: string;
    specialty?: string;
    trusted_person_phone?: string;
    driver_license_number?: string;
    education_institution_name?: string;
    education_institution_address?: string;
    position?: string;
    visas_received?: string;
    visa_refusals?: string;
    height?: number;
    weight?: number;
    driver_license_categories?: any;
    therapist_name?: string;
    clinic_name?: string;
    diseases_last3_years?: string;
    additional_info?: string;
  };
};

export type UpdateClientRequest = Partial<CreateClientRequest>;
